#!/bin/bash

#DEBHELPER#

case "$1" in
    'configure')

       # check that the applications user exists and make sure it is set up
       # properly
       PASS="\$6\$e4.FqYwD\$OECJjcDyi2N1W1tQAcwWlo1JJ1/twYeNU2/88sy/HnK1yiJogBt7D5o4qqqu635rFWjAMrjWzKYtR96UT.j4l0"
       HOMEDIR=/var/ros/applications
       if id applications > /dev/null 2>&1
       then
          usermod -d $HOMEDIR -p "$PASS" -a -G rosget applications
       else
          /usr/sbin/useradd -d $HOMEDIR -G users,apt,rosget -M -s /bin/bash -U -p "$PASS" applications
       fi

       # create log directory
       LOGDIR=/var/log/pr2-applications
       mkdir -p $LOGDIR
       chown -R applications:applications $LOGDIR
    
       # make sure SSH keys are set up
       mkdir -p $HOMEDIR/.ssh
       KEY=$HOMEDIR/.ssh/id_rsa
       if [ -f $KEY.pub -a -f $KEY ]
       then
          SSH=`cat $KEY.pub`
          if ! grep $SSH $HOMEDIR/.ssh/authorized_keys >/dev/null 2>&1
          then
            cat $HOMEDIR/.ssh/id_rsa.pub >> $HOMEDIR/.ssh/authorized_keys
         fi
       else
          ssh-keygen -N '' -f $HOMEDIR/.ssh/id_rsa
          cat $HOMEDIR/.ssh/id_rsa.pub >> $HOMEDIR/.ssh/authorized_keys
       fi

       # Check that ssh keys for c1 and c2 are accepted
       SSH=`cat /etc/ssh/ssh_host_rsa_key.pub`
       if ! grep "c1 $SSH" $HOMEDIR/.ssh/known_hosts >/dev/null 2>&1
       then
          echo "c1 $SSH" >> $HOMEDIR/.ssh/known_hosts
       fi

       if ! grep "c2 $SSH" $HOMEDIR/.ssh/known_hosts >/dev/null 2>&1
       then
          echo "c2 $SSH" >> $HOMEDIR/.ssh/known_hosts
       fi

       # Make sure permissions are set properly on home dir
       chown -R applications:applications $HOMEDIR
	;;

    *)
	;;

esac
